# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ouractl < Formula
  desc "A command line tool for your Oura Ring data"
  homepage "https://github.com/hagelstam/ouractl"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.4.0/ouractl_Darwin_x86_64.tar.gz"
      sha256 "dfadf1d3d52ecc27375ec2ceb837c67b00b855119ea579139117c25b61060a07"

      define_method(:install) do
        bin.install "ouractl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.4.0/ouractl_Darwin_arm64.tar.gz"
      sha256 "fa746e8b6672e3c9b6731056c57c65088cfb180010c007d10ffb41e3a146eba0"

      define_method(:install) do
        bin.install "ouractl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.4.0/ouractl_Linux_x86_64.tar.gz"
      sha256 "bd67d6f9fa36777241b5d0848354e58e46fd1cfcb5910d078027a2b379c5ebf9"
      define_method(:install) do
        bin.install "ouractl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.4.0/ouractl_Linux_arm64.tar.gz"
      sha256 "20b7390f9b2e2f53aa25f635f896fb039272a7701a97bb3e59b31dd25ed8276a"
      define_method(:install) do
        bin.install "ouractl"
      end
    end
  end

  test do
    system "#{bin}/ouractl", "--version"
  end
end
