# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ouractl < Formula
  desc "A command line tool for your Oura Ring data"
  homepage "https://github.com/hagelstam/ouractl"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.3.0/ouractl_Darwin_x86_64.tar.gz"
      sha256 "d5e94609460df7eb3cbb2fc6ba9fc760d433ebb08563275192d5bfdd5c74abd1"

      define_method(:install) do
        bin.install "ouractl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.3.0/ouractl_Darwin_arm64.tar.gz"
      sha256 "20e4a54028e8baa7147e4660fbb0691f54dec17df9e49e1774641d1c5c1593c1"

      define_method(:install) do
        bin.install "ouractl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.3.0/ouractl_Linux_x86_64.tar.gz"
      sha256 "b6c5930b329d04a26d4e32b3292b5b219306c3fc3a697cc824eb8fe78e41cb89"
      define_method(:install) do
        bin.install "ouractl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hagelstam/ouractl/releases/download/v0.3.0/ouractl_Linux_arm64.tar.gz"
      sha256 "f01ffb44e1a1d87768d4fdde0596bd3625796fe3fd34ba44410529edbcc6bc48"
      define_method(:install) do
        bin.install "ouractl"
      end
    end
  end

  test do
    system "#{bin}/ouractl", "--version"
  end
end
